version: '2'

services:
    jaeger-collector:
      image: jaegertracing/jaeger-collector:latest
      volumes:
        - "/Users/lunan/workspace/dockercompose/jaeger/strategies.json:/etc/jaeger/strategies.json"
      command:
        - "--cassandra.keyspace=jaeger_v1_dc1"
        - "--cassandra.servers=cassandra"
        - "--sampling.strategies-file=/etc/jaeger/strategies.json"
        - "--sampling.strategies-reload-interval=60s"
        #- "--collector.zipkin.host-port=9411"
        #- "--sampling.initial-sampling-probability=.5"
        #- "--sampling.target-samples-per-second=.01"
      environment:
        - SAMPLING_CONFIG_TYPE=file
      ports:
        - "14269:14269"
        - "14268:14268"
        - "14250:14250"
        - "9411:9411"
      restart: on-failure
      depends_on:
        - cassandra-schema

    jaeger-query:
      image: jaegertracing/jaeger-query:latest
      command: ["--cassandra.keyspace=jaeger_v1_dc1", "--cassandra.servers=cassandra"]
      ports:
        - "16686:16686"
        - "16687"
      restart: on-failure
      depends_on:
        - cassandra-schema

    jaeger-agent:
      image: jaegertracing/jaeger-agent:latest
      command: ["--reporter.grpc.host-port=jaeger-collector:14250"]
      ports:
        - "5775:5775/udp"
        - "6831:6831/udp"
        - "6832:6832/udp"
        - "5778:5778"
      restart: on-failure
      depends_on:
        - jaeger-collector

    cassandra:
      image: cassandra:4.0
      volumes:
        - /Users/lunan/workspace/dockercompose/data/cassandra:/var/lib/cassandra
      ports:
        - "9042:9042"

    cassandra-schema:
      image: jaegertracing/jaeger-cassandra-schema
      depends_on:
        - cassandra

#docker run --env STORAGE=cassandra --env CASSANDRA_CONTACT_POINTS=10.185.9.133:9042 --env JAVA_OPTS="-Xms512m" jaegertracing/spark-dependencies