version: '2'

networks:
  consul_cluser:
      driver: bridge

services:
  consul1: 
    image: consul:1.2.2
    container_name: consul1
    restart: always
    networks:
      - consul_cluser
    command: agent -server -client=0.0.0.0 -bootstrap-expect=3 -node=consul1 -datacenter=dc1
  consul2:
    image: consul:1.2.2
    container_name: consul2
    networks:
      - consul_cluser
    restart: always
    command: agent -server -client=0.0.0.0 -retry-join=consul1 -node=consul2 -datacenter=dc1
  consul3:
    image: consul:1.2.2
    container_name: consul3
    networks:
      - consul_cluser
    restart: always
    command: agent -server -client=0.0.0.0 -retry-join=consul1 -node=consul3 -datacenter=dc1
  consul4:
    image: consul:1.2.2
    container_name: consul4
    networks:
      - consul_cluser
    restart: always
    ports:
      - 8500:8500
    command: agent -client=0.0.0.0 -retry-join=consul1 -ui -node=client1 -datacenter=dc1
  # consul5:
  #   image: consul:1.2.2
  #   container_name: consul5
  #   networks:
  #     - consul_cluser
  #   restart: always
  #   command: agent -server -client=0.0.0.0 -bootstrap-expect=3 -node=consul5 -datacenter=dc2
  # consul6:
  #   image: consul:1.2.2
  #   container_name: consul6
  #   networks:
  #     - consul_cluser
  #   restart: always
  #   command: agent -server -client=0.0.0.0 -retry-join=consul5 -node=consul6 -datacenter=dc2
  # consul7:
  #   image: consul:1.2.2
  #   container_name: consul7
  #   networks:
  #     - consul_cluser
  #   restart: always
  #   command: agent -server -client=0.0.0.0 -retry-join=consul5 -node=consul7 -datacenter=dc2
  # consul8:
  #   image: consul:1.2.2
  #   container_name: consul8
  #   networks:
  #     - consul_cluser
  #   restart: always
  #   ports:
  #     - 8501:8500
  #   command: agent -client=0.0.0.0 -retry-join=consul5 -ui -node=client2 -datacenter=dc2