version: '3'
services:
  elasticsearch:
    image: elasticsearch:7.9.1
    container_name: "elasticsearch"
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - cluster.name=tommy-es
      - bootstrap.memory_lock=true
      - discovery.type=single-node
    volumes:
      - ./data:/usr/share/elasticsearch/data

  kibana:
    image: kibana:7.9.1
    container_name: kibana
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601