version: '2'

networks:
  kafka_cluser:
      driver: bridge

services:
  zookeeper:
    image: wurstmeister/zookeeper   
    hostname: zookeeper-local
    ports:
      - "2181:2181"                 
    networks:
     - kafka_cluser
  broker01:
    image: wurstmeister/kafka       
    depends_on:
      - zookeeper
    hostname: broker01
    volumes: 
        - /etc/localtime:/etc/localtime
    ports:
      - "9092:9092"
    environment:
      KAFKA_LISTENERS: PLAINTEXT://broker01:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 1
    networks:
     - kafka_cluser
  broker02:
    image: wurstmeister/kafka       
    depends_on:
      - zookeeper
    hostname: broker02
    volumes: 
        - /etc/localtime:/etc/localtime
    ports:
      - "9093:9093"
    environment:
      KAFKA_LISTENERS: PLAINTEXT://broker02:9093
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 2
    networks:
     - kafka_cluser
  broker03:
    image: wurstmeister/kafka       
    depends_on:
      - zookeeper
    hostname: broker03
    volumes: 
        - /etc/localtime:/etc/localtime
    ports:
      - "9094:9094"
    environment:
      KAFKA_LISTENERS: PLAINTEXT://broker03:9094
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 3
    networks:
     - kafka_cluser
  kafka-manager:  
    image: sheepkiller/kafka-manager    
    links:            
      - broker01
      - broker02
      - broker03          
    environment:
        ZK_HOSTS: zookeeper-local
        KAFKA_BROKERS: broker01:9092,broker02:9093,broker03:9094              
    ports:  
      - "9000:9000"                                 
    networks:
     - kafka_cluser

